version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail
    volumes:
      - "./logs:/var/log"
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  logmaker:
    build: "./log-maker"
    volumes:
      - "./logs:/var/log"
